'use client';

import { useState, useEffect } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { createClient } from '@/lib/supabase/client';
import Header from '@/components/dashboard/Header';
import Footer from '@/components/dashboard/Footer';
import LoadingSpinner from '@/components/ui/LoadingSpinner';

interface BriefStats {
  journalCount: number;
  documentCount: number;
  financialCount: number;
  timelineCount: number;
}

function buildPdfHtml(brief: string, generatedAt: string) {
  const escaped = brief.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

  return [
    '<!DOCTYPE html><html><head>',
    '<title>Full Situation Brief</title>',
    '<style>',
    'body{font-family:Georgia,"Times New Roman",serif;max-width:700px;margin:40px auto;padding:0 20px;color:#1a1a1a;line-height:1.7}',
    '.header{border-bottom:2px solid #333;padding-bottom:16px;margin-bottom:24px}',
    '.header h1{font-size:22px;margin:0 0 4px 0}',
    '.header p{font-size:13px;color:#666;margin:2px 0}',
    '.brief{font-size:14px;white-space:pre-wrap}',
    '.disclaimer{margin-top:32px;padding-top:16px;border-top:1px solid #ccc;font-size:11px;color:#999;font-style:italic}',
    '@media print{body{margin:20px}}',
    '</style></head><body>',
    '<div class="header">',
    '<h1>Full Situation Brief</h1>',
    '<p>Confidential — Prepared for Professional Review</p>',
    `<p>Generated: ${generatedAt}</p>`,
    '</div>',
    `<div class="brief">${escaped}</div>`,
    '<div class="disclaimer">',
    'This is an AI-generated brief based on user-provided data. It should be reviewed for accuracy and completeness before being used in any legal or professional context. Generated by Companion.',
    '</div>',
    '</body></html>',
  ].join('');
}

export default function BriefPage() {
  const router = useRouter();

  const [brief, setBrief] = useState<string | null>(null);
  const [stats, setStats] = useState<BriefStats | null>(null);
  const [generating, setGenerating] = useState(false);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);
  const [generatedAt, setGeneratedAt] = useState<string | null>(null);

  useEffect(() => {
    async function fetchCounts() {
      const supabase = createClient();
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) {
        router.push('/login');
        return;
      }

      const [j, d, f, t] = await Promise.all([
        supabase.from('journal_entries').select('id', { count: 'exact', head: true }),
        supabase.from('documents').select('id', { count: 'exact', head: true }),
        supabase.from('financial_items').select('id', { count: 'exact', head: true }),
        supabase.from('timeline_events').select('id', { count: 'exact', head: true }),
      ]);

      setStats({
        journalCount: j.count || 0,
        documentCount: d.count || 0,
        financialCount: f.count || 0,
        timelineCount: t.count || 0,
      });
      setLoading(false);
    }

    fetchCounts();
  }, [router]);

  async function handleGenerate() {
    setGenerating(true);
    setError('');

    try {
      const res = await fetch('/api/brief/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
      });

      const data = await res.json();

      if (!res.ok) {
        setError(data.error || 'Failed to generate brief.');
        setGenerating(false);
        return;
      }

      setBrief(data.brief);
      setStats(data.stats);
      setGeneratedAt(new Date().toISOString());
    } catch {
      setError('Failed to generate brief. Please try again.');
    } finally {
      setGenerating(false);
    }
  }

  const handleCopy = async () => {
    if (!brief) return;
    await navigator.clipboard.writeText(brief);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleExportPDF = () => {
    if (!brief || !generatedAt) return;

    const generated = new Date(generatedAt).toLocaleDateString('en-GB', {
      day: 'numeric',
      month: 'long',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });

    const html = buildPdfHtml(brief, generated);
    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const printWindow = window.open(url, '_blank');

    if (printWindow) {
      printWindow.addEventListener('afterprint', () => {
        URL.revokeObjectURL(url);
      });
      printWindow.addEventListener('load', () => {
        printWindow.print();
      });
    }
  };

  const totalItems = stats
    ? stats.journalCount + stats.documentCount + stats.financialCount + stats.timelineCount
    : 0;

  const generatedTimestamp = generatedAt
    ? new Date(generatedAt).toLocaleDateString('en-GB', {
        day: 'numeric',
        month: 'short',
        year: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
      })
    : null;

  return (
    <div className="min-h-screen bg-zinc-50 dark:bg-zinc-950 text-zinc-900 dark:text-zinc-100">
      <Header />

      <main className="px-6">
        <section className="max-w-3xl mx-auto pt-16 sm:pt-20 pb-12">
          <h1 className="text-4xl sm:text-5xl font-semibold tracking-tight leading-[1.05]">
            Brief
          </h1>
          <p className="mt-4 text-lg text-zinc-600 dark:text-zinc-400 max-w-xl">
            One document that pulls your journal, timeline, finances and vault into a
            readable summary.
          </p>
        </section>

        {loading ? (
          <section className="max-w-3xl mx-auto py-16 border-t border-zinc-200 dark:border-zinc-900">
            <div className="flex justify-center">
              <LoadingSpinner />
            </div>
          </section>
        ) : (
          <>
            <section className="max-w-3xl mx-auto py-12 border-t border-zinc-200 dark:border-zinc-900">
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-x-6 gap-y-8">
                <Stat label="Journal entries" count={stats?.journalCount || 0} href="/journal" />
                <Stat label="Timeline events" count={stats?.timelineCount || 0} href="/timeline" />
                <Stat label="Financial items" count={stats?.financialCount || 0} href="/finances" />
                <Stat label="Documents" count={stats?.documentCount || 0} href="/vault" />
              </div>
            </section>

            <section className="max-w-3xl mx-auto py-12 border-t border-zinc-200 dark:border-zinc-900">
              {totalItems === 0 ? (
                <p className="text-lg text-zinc-700 dark:text-zinc-300 leading-[1.7]">
                  Nothing to generate yet. Add journal entries, timeline events, or
                  financial items first.
                </p>
              ) : (
                <>
                  <p className="text-lg text-zinc-700 dark:text-zinc-300 leading-[1.7]">
                    When you&apos;re ready, the app will pull{' '}
                    <span className="font-medium text-zinc-900 dark:text-zinc-100">
                      {totalItems} {totalItems === 1 ? 'item' : 'items'}
                    </span>{' '}
                    into one document. Usually takes 15 to 30 seconds.
                  </p>
                  <div className="mt-6">
                    <button
                      onClick={handleGenerate}
                      disabled={generating}
                      className="inline-flex items-baseline gap-2 text-base font-medium border-b border-zinc-900 dark:border-zinc-100 pb-1 hover:text-zinc-600 dark:hover:text-zinc-400 hover:border-zinc-600 dark:hover:border-zinc-400 transition-colors disabled:opacity-50"
                    >
                      {generating ? 'Generating…' : brief ? 'Regenerate brief' : 'Generate full brief'}
                      {!generating && <span aria-hidden>→</span>}
                    </button>
                  </div>
                  {error && (
                    <p className="mt-6 text-sm text-red-600 dark:text-red-400">{error}</p>
                  )}
                </>
              )}
            </section>

            {brief && (
              <section className="max-w-3xl mx-auto py-12 border-t border-zinc-200 dark:border-zinc-900">
                <div className="flex items-baseline justify-between gap-4 flex-wrap mb-8">
                  <p className="text-xs uppercase tracking-[0.18em] text-zinc-500 dark:text-zinc-500">
                    Your brief
                  </p>
                  {generatedTimestamp && (
                    <p className="text-xs uppercase tracking-[0.18em] text-zinc-500 dark:text-zinc-500">
                      Generated {generatedTimestamp}
                    </p>
                  )}
                </div>

                <article className="border border-zinc-200 dark:border-zinc-900 bg-white dark:bg-zinc-900/40 rounded-lg p-8 sm:p-10">
                  <p className="text-[15px] leading-[1.8] text-zinc-800 dark:text-zinc-200 whitespace-pre-wrap">
                    {brief}
                  </p>
                </article>

                <p className="mt-4 text-xs text-zinc-500 dark:text-zinc-500">
                  Review carefully before sharing with any professional.
                </p>

                <div className="mt-8 flex items-center gap-5 text-xs uppercase tracking-[0.18em] text-zinc-500 dark:text-zinc-500">
                  <button
                    onClick={handleCopy}
                    className="hover:text-zinc-900 dark:hover:text-zinc-200 transition-colors"
                  >
                    {copied ? 'Copied' : 'Copy'}
                  </button>
                  <button
                    onClick={handleExportPDF}
                    className="hover:text-zinc-900 dark:hover:text-zinc-200 transition-colors"
                  >
                    Export PDF
                  </button>
                  <button
                    onClick={handleGenerate}
                    disabled={generating}
                    className="hover:text-zinc-900 dark:hover:text-zinc-200 transition-colors disabled:opacity-50"
                  >
                    {generating ? 'Regenerating…' : 'Regenerate'}
                  </button>
                </div>

                {stats && (
                  <p className="mt-8 text-xs uppercase tracking-[0.18em] text-zinc-500 dark:text-zinc-500">
                    Built from {stats.journalCount} journal{' '}
                    {stats.journalCount === 1 ? 'entry' : 'entries'} · {stats.timelineCount}{' '}
                    timeline {stats.timelineCount === 1 ? 'event' : 'events'} ·{' '}
                    {stats.financialCount} financial{' '}
                    {stats.financialCount === 1 ? 'item' : 'items'} · {stats.documentCount}{' '}
                    {stats.documentCount === 1 ? 'document' : 'documents'}
                  </p>
                )}
              </section>
            )}
          </>
        )}
      </main>

      <Footer />
    </div>
  );
}

function Stat({ label, count, href }: { label: string; count: number; href: string }) {
  return (
    <Link href={href} className="block group">
      <p className="text-xs uppercase tracking-[0.18em] text-zinc-500 dark:text-zinc-500 mb-2">
        {label}
      </p>
      <p className="text-5xl sm:text-6xl font-semibold tracking-tight text-zinc-900 dark:text-zinc-100 group-hover:text-zinc-600 dark:group-hover:text-zinc-400 transition-colors">
        {count}
      </p>
    </Link>
  );
}
