'use client';

import { useState } from 'react';
import Button from '@/components/ui/Button';

interface AISummarySectionProps {
  entryId: string;
  summary: string | null;
  generatedAt: string | null;
  entryTitle: string | null;
  incidentDate: string;
  onSummaryGenerated: (summary: string, generatedAt: string) => void;
}

function buildPdfHtml(title: string, date: string, generated: string, summary: string) {
  const escaped = summary.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

  return [
    '<!DOCTYPE html><html><head>',
    `<title>${title} - Summary</title>`,
    '<style>',
    'body{font-family:Georgia,"Times New Roman",serif;max-width:700px;margin:40px auto;padding:0 20px;color:#1a1a1a;line-height:1.6}',
    '.header{border-bottom:2px solid #333;padding-bottom:16px;margin-bottom:24px}',
    '.header h1{font-size:20px;margin:0 0 4px 0}',
    '.header p{font-size:13px;color:#666;margin:2px 0}',
    '.summary{font-size:14px;white-space:pre-wrap}',
    '.disclaimer{margin-top:32px;padding-top:16px;border-top:1px solid #ccc;font-size:11px;color:#999;font-style:italic}',
    '@media print{body{margin:20px}}',
    '</style></head><body>',
    '<div class="header">',
    `<h1>${title}</h1>`,
    `<p>Incident Date: ${date}</p>`,
    `<p>Summary Generated: ${generated}</p>`,
    '</div>',
    `<div class="summary">${escaped}</div>`,
    '<div class="disclaimer">',
    'This is an AI-generated summary. It should be reviewed for accuracy before being shared with legal or medical professionals. Generated by Companion.',
    '</div>',
    '</body></html>',
  ].join('');
}

export default function AISummarySection({
  entryId,
  summary,
  generatedAt,
  entryTitle,
  incidentDate,
  onSummaryGenerated,
}: AISummarySectionProps) {
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);

  const handleGenerate = async () => {
    setGenerating(true);
    setError('');

    try {
      const res = await fetch('/api/journal/summarise', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ entryId }),
      });

      if (!res.ok) {
        throw new Error('Failed to generate summary');
      }

      const data = await res.json();
      onSummaryGenerated(data.summary, new Date().toISOString());
    } catch {
      setError('Failed to generate summary. Please try again.');
    } finally {
      setGenerating(false);
    }
  };

  const handleCopy = async () => {
    if (!summary) return;
    await navigator.clipboard.writeText(summary);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleExportPDF = () => {
    if (!summary) return;

    const title = entryTitle || 'Journal Entry Summary';
    const date = new Date(incidentDate).toLocaleDateString('en-GB', {
      day: 'numeric',
      month: 'long',
      year: 'numeric',
    });
    const generated = generatedAt
      ? new Date(generatedAt).toLocaleDateString('en-GB', {
          day: 'numeric',
          month: 'short',
          year: 'numeric',
          hour: '2-digit',
          minute: '2-digit',
        })
      : '';

    const html = buildPdfHtml(title, date, generated, summary);
    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const printWindow = window.open(url, '_blank');

    if (printWindow) {
      printWindow.addEventListener('afterprint', () => {
        URL.revokeObjectURL(url);
      });
      printWindow.addEventListener('load', () => {
        printWindow.print();
      });
    }
  };

  return (
    <div>
      <h2 className="text-lg font-semibold text-zinc-900 dark:text-white mb-3">
        AI Summary
      </h2>

      {summary ? (
        <div className="bg-blue-50 dark:bg-blue-900/10 border border-blue-200 dark:border-blue-800 rounded-lg p-4">
          <p className="text-sm text-zinc-800 dark:text-zinc-200 whitespace-pre-wrap leading-relaxed">
            {summary}
          </p>
          {generatedAt && (
            <p className="text-xs text-zinc-500 dark:text-zinc-400 mt-3">
              Generated {new Date(generatedAt).toLocaleDateString('en-GB', {
                day: 'numeric',
                month: 'short',
                year: 'numeric',
                hour: '2-digit',
                minute: '2-digit',
              })}
            </p>
          )}
          <p className="text-xs text-zinc-500 dark:text-zinc-400 mt-1 italic">
            This is an AI-generated draft. Please review before sharing.
          </p>
          <div className="flex flex-wrap gap-2 mt-3">
            <Button size="sm" variant="outline" onClick={handleCopy}>
              {copied ? 'Copied!' : 'Copy Summary'}
            </Button>
            <Button size="sm" variant="outline" onClick={handleExportPDF}>
              Export PDF
            </Button>
            <Button
              size="sm"
              variant="outline"
              onClick={handleGenerate}
              isLoading={generating}
            >
              Regenerate
            </Button>
          </div>
        </div>
      ) : (
        <div className="bg-zinc-50 dark:bg-zinc-800/50 border border-zinc-200 dark:border-zinc-700 rounded-lg p-6 text-center">
          <p className="text-sm text-zinc-500 dark:text-zinc-400 mb-3">
            Generate a professional summary of this entry for sharing with your lawyer or therapist.
          </p>
          <Button onClick={handleGenerate} isLoading={generating}>
            Generate AI Summary
          </Button>
        </div>
      )}

      {error && (
        <p className="mt-2 text-sm text-red-500">{error}</p>
      )}
    </div>
  );
}
